name: Blaze-PvP
main: pl.polskistevek.blazepvp.Blaze
version: 1.2dev-03.07.2019
authors: [PolskiStevek, jambosmaha]
softdepend: [Blaze-API]

commands:
  setspawn:
    description: Ustawianie lobby glownego serwera
  yt:
    description: Informacje o Randze YT
    aliases: youtube
  tp:
    description: Teleportacja do gracza
  help:
    aliases: pomoc
    description: Lista dostepnych komend
  list:
    aliases: online
    description: Lista graczy
  blaze:
    description: Reloadowanie core + info
  yt+:
    description: Komenda yt+
  miniyt:
   description: informacje o miniyt
  putin:
    description: Informacje o randze putin
  live:
    description: Inroamcje o liveach.
  discord:
    description: link do dc
  putin+:
    description: Info o putinie +
  putin++:
    description: Info o putinie ++
  gamemode:
    aliases: gm
    description: Zmiana trybu gry
  helpop:
    description: Kontakt z administracja
  gang:
    description: Blad
  whois:
    description: informacje o graczu
  bc:
    aliases: broadcast
    description: Broadcast
  fly:
    description: Latanie
  heal:
    description: Leczenie
  kick:
    description: Wyrzucanie