name: Blaze-PvP
main: pl.polskistevek.blazepvp.Blaze
version: 1.0dev-03.07.2019
authors: [PolskiStevek, jambosmaha]
depend: [Blaze-API]

commands:
  setspawn:
    description: Ustawianie lobby glownego serwera
  yt:
    description: Informacje o Randze YT
    aliases: youtube
  tp:
    description: Teleportacja do gracza
  help:
    aliases: pomoc
    description: Lista dostepnych komend
  list:
    aliases: online
    description: Lista graczy
  blaze:
    description: Reloadowanie core
    yt+:
     description: Komenda yt+
     miniyt:
      description: informacje o miniyt
  putin:
   description: Informacje o randze putin
    live:
  description: Inroamcje o liveach.
   kosz:
    description: usuwanie syf itków
  discord:
     description: link do dc
  www:
   description: Strona www
     whois:
       description:  ip gracza itp info

